apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: htcondor-central-manager
  name: htcondor-central-manager
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: htcondor-central-manager
    spec:
      containers:
      - name: htcondor-central-manager
        image: zzxuanyuan/htcondor-central-manager:github
        resources:
          requests:
            memory: "1.0Gi"
            cpu: "500m"
          limits:
            memory: "1.0Gi"
            cpu: "500m"
        env:
        - name: CONDOR_HOST
          value: "htcondor-central-manager"
        - name: SEC_PASSWORD_FILE
          value: "/etc/condor/pool_password/password"
        volumeMounts:
          - name: pool-password
            mountPath: /etc/condor/pool_password
        ports:
        - containerPort: 9618
          protocol: TCP
      volumes:
      - name: pool-password
        secret:
          defaultMode: 0600
          secretName: htcondor-pool-password
